name: Update Cryptocurrency Prices

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests pillow matplotlib
      - name: Update README
        run: python update-prices.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md BTC.png ETH.png LTC.png ETH_donations.png BNB_donations.png crypto_prices.gif transactions_graph.png
          git commit -m "Update cryptocurrency prices and donation balances"
          git push
